#!/usr/bin/env python3
"""生成圆屏静态表盘和屏保时间专用原生字体。"""

from __future__ import annotations

import math
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


BOARD_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BOARD_DIR.parents[2]
ASSET_DIR = BOARD_DIR / "display" / "assets"
FONT_DIR = BOARD_DIR / "display" / "fonts"
FONT_PATH = PROJECT_ROOT / "managed_components" / "78__xiaozhi-fonts" / "ttf" / "puhui-basic.ttf"
SIZE = 360
SCALE = 4
TIME_GLYPH_TRACKING = 2


def make_dial() -> Image.Image:
    """生成不含动态文字和秒针的表盘底图。"""
    canvas = SIZE * SCALE
    image = Image.new("RGB", (canvas, canvas), "#050607")
    draw = ImageDraw.Draw(image)
    def box(a: int, b: int, c: int, d: int) -> tuple[int, int, int, int]:
        return a * SCALE, b * SCALE, c * SCALE, d * SCALE

    draw.ellipse(box(6, 6, 354, 354), fill="#15191d", outline="#454b52", width=2 * SCALE)
    draw.ellipse(box(17, 17, 343, 343), fill="#0a0d10", outline="#272c31", width=SCALE)
    center = canvas / 2
    radius = 164 * SCALE
    draw.ellipse((center - radius, center - radius, center + radius, center + radius),
                 outline="#31363b", width=SCALE)
    for tick in range(60):
        if tick in (0, 30):
            continue
        major = tick % 5 == 0
        length = (12 if major else 6) * SCALE
        width = (3 if major else 1) * SCALE
        angle = math.radians(tick * 6 - 90)
        inner = radius - length
        start = (center + inner * math.cos(angle), center + inner * math.sin(angle))
        end = (center + radius * math.cos(angle), center + radius * math.sin(angle))
        draw.line((*start, *end), fill="#ffffff" if major else "#8b9299", width=width)
    return image.resize((SIZE, SIZE), Image.Resampling.LANCZOS)


def write_rgb565(image: Image.Image, output: Path) -> None:
    """写入小端 RGB565 原始像素。"""
    data = bytearray()
    for red, green, blue in image.getdata():
        pixel = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        data.extend(struct.pack("<H", pixel))
    output.write_bytes(data)


def font_source() -> str:
    """生成只包含时间字符的 64px 原生 A8 字体。"""
    font = ImageFont.truetype(FONT_PATH, 64)
    chars = "-:0123456789"
    bitmap = bytearray()
    glyphs = []
    digit_advance = max(round(font.getlength(ch)) for ch in "0123456789") + TIME_GLYPH_TRACKING
    for ch in chars:
        left, top, right, bottom = font.getbbox(ch, anchor="ls", stroke_width=3)
        glyph = Image.new("L", (right - left, bottom - top), 0)
        ImageDraw.Draw(glyph).text(
            (-left, -top), ch, font=font, anchor="ls", fill=255,
            stroke_width=3, stroke_fill=255)
        offset = len(bitmap)
        bitmap.extend(glyph.tobytes())
        advance = (digit_advance if ch.isdigit()
                   else round(font.getlength(ch)) + TIME_GLYPH_TRACKING)
        glyphs.append((ord(ch), offset, advance, right - left, bottom - top, left, bottom))

    values = ",\n".join(
        f"    {{{code}, {offset}, {advance}, {width}, {height}, {ofs_x}, {ofs_y}}}"
        for code, offset, advance, width, height, ofs_x, ofs_y in glyphs)
    bitmap_text = ", ".join(f"0x{value:02x}" for value in bitmap)
    return f'''/** Generated by boards/movecall-moji2-esp32c5/scripts/generate_ui_assets.py. */
#include "ui_fonts.h"
#include <cstddef>
#include <cstdint>

namespace {{
struct Glyph {{
    uint32_t codepoint;
    uint32_t bitmap_offset;
    uint16_t advance_width;
    uint16_t box_width;
    uint16_t box_height;
    int16_t offset_x;
    int16_t offset_y;
}};

LV_ATTRIBUTE_LARGE_CONST const uint8_t kBitmap[] = {{{bitmap_text}}};
constexpr Glyph kGlyphs[] = {{
{values}
}};

bool GetGlyph(const lv_font_t*, lv_font_glyph_dsc_t* dsc, uint32_t letter, uint32_t) {{
    for (size_t i = 0; i < sizeof(kGlyphs) / sizeof(kGlyphs[0]); ++i) {{
        const auto& glyph = kGlyphs[i];
        if (glyph.codepoint != letter) continue;
        dsc->adv_w = glyph.advance_width;
        dsc->box_w = glyph.box_width;
        dsc->box_h = glyph.box_height;
        dsc->ofs_x = glyph.offset_x;
        dsc->ofs_y = glyph.offset_y;
        dsc->stride = glyph.box_width;
        dsc->format = LV_FONT_GLYPH_FORMAT_A8;
        dsc->gid.index = i;
        return true;
    }}
    return false;
}}

const void* GetBitmap(lv_font_glyph_dsc_t* dsc, lv_draw_buf_t*) {{
    const size_t index = dsc->gid.index;
    return index < sizeof(kGlyphs) / sizeof(kGlyphs[0]) ?
        kBitmap + kGlyphs[index].bitmap_offset : nullptr;
}}
}}  // namespace

const lv_font_t font_puhui_time_64 = {{
    .get_glyph_dsc = GetGlyph,
    .get_glyph_bitmap = GetBitmap,
    .release_glyph = nullptr,
    .line_height = 82,
    .base_line = 16,
    .subpx = LV_FONT_SUBPX_NONE,
    .kerning = LV_FONT_KERNING_NONE,
    .static_bitmap = 1,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = nullptr,
    .fallback = nullptr,
    .user_data = nullptr,
}};
'''


def main() -> None:
    """生成并保存屏保资源。"""
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    dial = make_dial()
    dial.save(ASSET_DIR / "screensaver_dial.png", optimize=True)
    write_rgb565(dial, ASSET_DIR / "screensaver_dial.rgb565")
    (FONT_DIR / "font_puhui_time_64.cc").write_text(font_source(), encoding="utf-8")


if __name__ == "__main__":
    main()
